/**
 * 家庭冰箱库存 App - 内置菜谱数据库
 * 包含 130+ 道真实中文菜谱（川菜、减脂餐、家常快手菜）
 */
const RecipeDB = [

  // ============ 川菜 (55道) ============
  {id:'s1',name:'麻婆豆腐',cuisine:'川菜',difficulty:'简单',cookTime:20,calories:280,tags:['川菜','经典'],isSichuan:true,ingredients:['豆腐','牛肉末','豆瓣酱','花椒','辣椒面','蒜苗','姜','蒜'],steps:['豆腐切块焯水备用','锅中热油炒香牛肉末','加豆瓣酱、辣椒面炒出红油','加适量水烧开','放入豆腐小火炖5分钟','水淀粉勾芡','撒花椒粉和蒜苗出锅']},
  {id:'s2',name:'宫保鸡丁',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:350,tags:['川菜','经典'],isSichuan:true,ingredients:['鸡胸肉','花生米','干辣椒','花椒','葱','姜','蒜','醋','糖','酱油','淀粉'],steps:['鸡胸肉切丁加料酒淀粉腌制','调碗汁：醋、糖、酱油、淀粉水','锅中炸花生米捞出备用','爆香干辣椒花椒','滑炒鸡丁至变色','倒入料汁翻炒','最后加花生米出锅']},
  {id:'s3',name:'回锅肉',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:420,tags:['川菜','经典'],isSichuan:true,ingredients:['五花肉','青蒜','豆瓣酱','豆豉','姜','料酒','糖'],steps:['五花肉整块煮至八成熟','切薄片备用','锅中不放油煸炒肉片出油','加豆瓣酱豆豉炒香','加青蒜段翻炒','加少许糖调味出锅']},
  {id:'s4',name:'水煮牛肉',cuisine:'川菜',difficulty:'中等',cookTime:35,calories:380,tags:['川菜','麻辣'],isSichuan:true,ingredients:['牛肉','豆芽','生菜','豆瓣酱','干辣椒','花椒','姜','蒜','辣椒面'],steps:['牛肉切片用料酒淀粉腌制','炒香豆瓣酱加水煮沸','烫熟豆芽生菜铺碗底','滑入牛肉片煮至变色','倒入碗中','撒辣椒面花椒蒜末','浇热油激香']},
  {id:'s5',name:'鱼香肉丝',cuisine:'川菜',difficulty:'中等',cookTime:20,calories:320,tags:['川菜','经典'],isSichuan:true,ingredients:['猪里脊','木耳','胡萝卜','青椒','泡椒','姜','蒜','葱','醋','糖','酱油','淀粉'],steps:['猪肉切丝腌制','木耳胡萝卜青椒切丝','调鱼香汁：醋糖酱油淀粉水','炒肉丝变色盛出','炒香泡椒姜蒜','加配菜翻炒','加肉丝和鱼香汁翻炒出锅']},
  {id:'s6',name:'辣子鸡',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:450,tags:['川菜','麻辣'],isSichuan:true,ingredients:['鸡腿肉','干辣椒','花椒','姜','蒜','料酒','酱油','糖','芝麻'],steps:['鸡腿切小块腌制','热油炸至金黄酥脆','留底油炒香干辣椒花椒','加鸡块翻炒','加糖芝麻调味出锅']},
  {id:'s7',name:'毛血旺',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:420,tags:['川菜','麻辣'],isSichuan:true,ingredients:['鸭血','毛肚','午餐肉','豆芽','豆皮','豆瓣酱','干辣椒','花椒','姜蒜'],steps:['鸭血切块焯水','炒香豆瓣酱加水煮汤','豆芽豆皮烫熟铺碗底','鸭血毛肚午餐肉煮入味','倒入碗中撒辣椒花椒','浇热油']},
  {id:'s8',name:'酸菜鱼',cuisine:'川菜',difficulty:'中等',cookTime:35,calories:320,tags:['川菜','酸辣'],isSichuan:true,ingredients:['草鱼','酸菜','泡椒','姜','蒜','花椒','干辣椒','蛋清','淀粉'],steps:['鱼片片好加蛋清淀粉腌制','鱼骨煎香加酸菜炒','加水煮汤','捞出鱼骨酸菜铺碗底','滑入鱼片煮至变白','连汤倒入碗中','撒辣椒花椒浇热油']},
  {id:'s9',name:'水煮鱼',cuisine:'川菜',difficulty:'中等',cookTime:35,calories:380,tags:['川菜','麻辣'],isSichuan:true,ingredients:['草鱼','豆芽','豆瓣酱','干辣椒','花椒','辣椒面','姜','蒜','蛋清','淀粉'],steps:['鱼片片好腌制','炒香豆瓣酱加水煮开','豆芽烫熟铺碗底','滑入鱼片煮熟','倒入碗中撒辣椒面花椒蒜末','浇热油']},
  {id:'s10',name:'干煸四季豆',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:180,tags:['川菜','素菜'],isSichuan:true,ingredients:['四季豆','干辣椒','花椒','蒜','盐','糖'],steps:['四季豆去筋掰段','热油炸至表皮起皱','留底油炒香干辣椒花椒蒜','加四季豆翻炒','加盐糖调味出锅']},
  {id:'s11',name:'夫妻肺片',cuisine:'川菜',difficulty:'中等',cookTime:40,calories:300,tags:['川菜','凉菜'],isSichuan:true,ingredients:['牛腱子','牛舌','牛肚','花生碎','芝麻','辣椒油','花椒粉','酱油','醋'],steps:['牛腱牛舌牛肚卤熟','切薄片摆盘','调红油汁：辣椒油花椒粉酱油醋','浇在肉片上','撒花生碎芝麻葱花']},
  {id:'s12',name:'口水鸡',cuisine:'川菜',difficulty:'中等',cookTime:35,calories:350,tags:['川菜','凉菜'],isSichuan:true,ingredients:['鸡腿','花生碎','芝麻','辣椒油','花椒油','酱油','醋','糖','葱姜'],steps:['鸡腿煮熟冰水浸泡','剁块摆盘','调口水汁：辣椒油花椒油酱油醋糖','浇在鸡块上','撒花生碎芝麻葱花']},
  {id:'s13',name:'担担面',cuisine:'川菜',difficulty:'简单',cookTime:20,calories:380,tags:['川菜','面食'],isSichuan:true,ingredients:['面条','猪肉末','芽菜','花生碎','芝麻酱','辣椒油','花椒粉','葱'],steps:['炒香肉末加芽菜','调底料：芝麻酱辣椒油花椒粉','煮面捞入碗中','加肉末芽菜花生碎葱花']},
  {id:'s14',name:'东坡肘子',cuisine:'川菜',difficulty:'困难',cookTime:120,calories:550,tags:['川菜','大菜'],isSichuan:true,ingredients:['猪肘','冰糖','酱油','料酒','姜','葱','八角','桂皮'],steps:['猪肘焯水去毛','炒糖色加酱油料酒','加姜葱八角桂皮','加水没过猪肘慢炖2小时','收汁出锅']},
  {id:'s15',name:'干锅花菜',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:200,tags:['川菜','素菜'],isSichuan:true,ingredients:['花菜','五花肉','干辣椒','花椒','蒜','酱油','盐'],steps:['花菜掰小朵焯水','五花肉煸出油','加干辣椒花椒蒜炒香','加花菜大火翻炒','加酱油盐调味出锅']},
  {id:'s16',name:'鱼香茄子',cuisine:'川菜',difficulty:'简单',cookTime:20,calories:250,tags:['川菜','素菜'],isSichuan:true,ingredients:['茄子','豆瓣酱','蒜','姜','葱','醋','糖','酱油','淀粉'],steps:['茄子切条油炸至软','调鱼香汁','炒香豆瓣酱姜蒜','加茄子倒入鱼香汁','收汁撒葱花']},
  {id:'s17',name:'蚂蚁上树',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:280,tags:['川菜','家常'],isSichuan:true,ingredients:['粉丝','猪肉末','豆瓣酱','葱','姜','蒜','酱油'],steps:['粉丝泡软','炒香肉末加豆瓣酱','加姜蒜炒香','加粉丝和少量水','翻炒至粉丝透明','撒葱花出锅']},
  {id:'s18',name:'水煮肉片',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:380,tags:['川菜','麻辣'],isSichuan:true,ingredients:['猪里脊','生菜','豆瓣酱','干辣椒','花椒','辣椒面','姜','蒜','蛋清','淀粉'],steps:['肉片腌制','炒香豆瓣酱加水煮','烫生菜铺碗底','滑入肉片煮熟倒入碗中','撒辣椒面花椒蒜末','浇热油']},
  {id:'s19',name:'川味回锅肉',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:400,tags:['川菜','经典'],isSichuan:true,ingredients:['五花肉','蒜苗','豆瓣酱','豆豉','姜','料酒','糖'],steps:['五花肉整块煮熟','切薄片','煸炒出油','加豆瓣酱豆豉炒香','加蒜苗翻炒','加糖调味']},
  {id:'s20',name:'蒜泥白肉',cuisine:'川菜',difficulty:'简单',cookTime:25,calories:380,tags:['川菜','凉菜'],isSichuan:true,ingredients:['五花肉','蒜','辣椒油','酱油','醋','糖','葱'],steps:['五花肉整块煮熟','切薄片摆盘','调蒜泥汁：蒜泥辣椒油酱油醋糖','浇在肉片上']},
  {id:'s21',name:'麻辣香锅',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:450,tags:['川菜','麻辣'],isSichuan:true,ingredients:['虾','午餐肉','藕','土豆','花菜','干辣椒','花椒','豆瓣酱','姜蒜'],steps:['各种食材切好焯水油炸','炒香干辣椒花椒豆瓣酱','加所有食材大火翻炒','加调料炒匀出锅']},
  {id:'s22',name:'冒菜',cuisine:'川菜',difficulty:'简单',cookTime:20,calories:320,tags:['川菜','麻辣'],isSichuan:true,ingredients:['午餐肉','土豆','藕','豆皮','豆芽','豆瓣酱','花椒','干辣椒','姜蒜'],steps:['炒香豆瓣酱加汤','煮沸后加入各种食材','煮熟捞出装碗','撒花椒干辣椒浇热油']},
  {id:'s23',name:'川北凉粉',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:200,tags:['川菜','凉菜'],isSichuan:true,ingredients:['凉粉','辣椒油','花椒粉','酱油','醋','蒜','葱','花生碎'],steps:['凉粉切条摆盘','调汁：辣椒油花椒粉酱油醋蒜','浇在凉粉上','撒花生碎葱花']},
  {id:'s24',name:'宫保虾球',cuisine:'川菜',difficulty:'中等',cookTime:20,calories:320,tags:['川菜','海鲜'],isSichuan:true,ingredients:['大虾','花生米','干辣椒','花椒','葱','姜','蒜','醋','糖','酱油','淀粉'],steps:['虾去壳开背腌制','调宫保汁','炸花生米','炒香干辣椒花椒','滑炒虾球至变色','加料汁翻炒','加花生米出锅']},
  {id:'s25',name:'辣子肥肠',cuisine:'川菜',difficulty:'中等',cookTime:40,calories:480,tags:['川菜','麻辣'],isSichuan:true,ingredients:['猪大肠','干辣椒','花椒','姜','蒜','料酒','酱油','糖'],steps:['肥肠洗净焯水卤熟','切段','油炸至金黄','炒香干辣椒花椒','加肥肠翻炒','调味出锅']},
  {id:'s26',name:'泡椒凤爪',cuisine:'川菜',difficulty:'简单',cookTime:30,calories:250,tags:['川菜','凉菜'],isSichuan:true,ingredients:['鸡爪','泡椒','花椒','姜','料酒','盐','白醋'],steps:['鸡爪焯水煮熟','冰水浸泡','加泡椒花椒姜盐醋','冷藏浸泡4小时以上']},
  {id:'s27',name:'沸腾鱼',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:380,tags:['川菜','麻辣'],isSichuan:true,ingredients:['草鱼','豆芽','干辣椒','花椒','豆瓣酱','蛋清','淀粉','姜蒜'],steps:['鱼片腌制','豆芽烫熟铺碗底','鱼片滑熟铺在豆芽上','大量干辣椒花椒撒表面','浇滚烫热油']},
  {id:'s28',name:'麻花回锅肉',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:450,tags:['川菜','创新'],isSichuan:true,ingredients:['五花肉','小麻花','蒜苗','豆瓣酱','豆豉','姜','糖'],steps:['五花肉煮至八成熟切薄片','煸炒出油','加豆瓣酱豆豉','加蒜苗翻炒','加小麻花快速翻炒出锅']},
  {id:'s29',name:'糖醋里脊',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:380,tags:['川菜','酸甜'],isSichuan:true,ingredients:['猪里脊','番茄酱','醋','糖','淀粉','鸡蛋','芝麻'],steps:['里脊切条腌制挂糊','油炸至金黄酥脆','调糖醋汁：番茄酱醋糖','裹上糖醋汁','撒芝麻出锅']},
  {id:'s30',name:'干锅土豆片',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:220,tags:['川菜','素菜'],isSichuan:true,ingredients:['土豆','五花肉','干辣椒','花椒','蒜','豆瓣酱','葱'],steps:['土豆切片','五花肉煸出油','加豆瓣酱干辣椒花椒炒香','加土豆片翻炒至熟','撒葱花出锅']},
  {id:'s31',name:'钵钵鸡',cuisine:'川菜',difficulty:'简单',cookTime:25,calories:300,tags:['川菜','凉菜'],isSichuan:true,ingredients:['鸡腿','藕片','土豆','豆皮','竹签','辣椒油','花椒油','芝麻','鸡汤'],steps:['各种食材煮熟穿串','调红油汤底：辣椒油花椒油芝麻鸡汤','浸泡入味即可']},
  {id:'s32',name:'豆瓣鱼',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:320,tags:['川菜','经典'],isSichuan:true,ingredients:['草鱼','豆瓣酱','姜','蒜','葱','料酒','糖','淀粉'],steps:['鱼两面煎金黄','炒香豆瓣酱姜蒜','加水和鱼煮10分钟','收汁装盘撒葱花']},
  {id:'s33',name:'泡椒牛肉',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:300,tags:['川菜','快手'],isSichuan:true,ingredients:['牛肉','泡椒','姜','蒜','葱','酱油','淀粉','料酒'],steps:['牛肉切片腌制','泡椒切碎','热油炒牛肉变色盛出','炒香泡椒姜蒜','加牛肉翻炒出锅']},
  {id:'s34',name:'虎皮青椒',cuisine:'川菜',difficulty:'简单',cookTime:10,calories:150,tags:['川菜','素菜'],isSichuan:true,ingredients:['青椒','蒜','酱油','醋','糖','豆豉'],steps:['青椒整根煎至表皮起皱','炒香蒜末豆豉','加酱油醋糖调汁','浇在青椒上翻炒出锅']},
  {id:'s35',name:'宜宾燃面',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:400,tags:['川菜','面食'],isSichuan:true,ingredients:['面条','芽菜','花生碎','芝麻','辣椒油','花椒油','葱','酱油'],steps:['煮面捞出沥干','加辣椒油花椒油拌匀','加芽菜花生碎芝麻葱花酱油','拌匀即可']},
  {id:'s36',name:'水煮豆花',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:200,tags:['川菜','素菜'],isSichuan:true,ingredients:['嫩豆腐','豆瓣酱','干辣椒','花椒','蒜','葱','淀粉'],steps:['豆瓣酱炒香加水煮开','嫩豆腐切块放入煮5分钟','勾芡装碗','撒辣椒花椒蒜末浇热油']},
  {id:'s37',name:'孜然牛肉',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:340,tags:['川菜','快手'],isSichuan:true,ingredients:['牛肉','孜然','辣椒面','芝麻','洋葱','酱油','淀粉'],steps:['牛肉切片腌制','洋葱切丝','热油炒牛肉变色盛出','炒香洋葱','加牛肉孜然辣椒面翻炒出锅']},
  {id:'s38',name:'蜀香排骨',cuisine:'川菜',difficulty:'中等',cookTime:45,calories:480,tags:['川菜','大菜'],isSichuan:true,ingredients:['排骨','豆瓣酱','花椒','干辣椒','姜','蒜','料酒','糖'],steps:['排骨焯水','炒香豆瓣酱花椒','加排骨翻炒加料酒','加水炖煮30分钟','收汁加干辣椒蒜末']},
  {id:'s39',name:'口水藕片',cuisine:'川菜',difficulty:'简单',cookTime:10,calories:160,tags:['川菜','凉菜'],isSichuan:true,ingredients:['藕','辣椒油','花椒油','酱油','醋','糖','蒜','葱'],steps:['藕切片焯水','过冰水保持脆爽','调红油汁浇上','撒蒜末葱花']},
  {id:'s40',name:'豆花牛肉',cuisine:'川菜',difficulty:'中等',cookTime:20,calories:360,tags:['川菜','创新'],isSichuan:true,ingredients:['牛肉','嫩豆腐','豆瓣酱','花椒','干辣椒','姜','蒜','淀粉'],steps:['牛肉切末腌制','炒香豆瓣酱加汤','嫩豆腐切块煮入味','牛肉末滑熟','勾芡出锅撒花椒辣椒']},
  {id:'s41',name:'川味腊肠',cuisine:'川菜',difficulty:'简单',cookTime:10,calories:400,tags:['川菜','腊味'],isSichuan:true,ingredients:['川味腊肠','蒜苗','干辣椒'],steps:['腊肠切片蒸熟','蒜苗切段','炒香干辣椒','加腊肠蒜苗翻炒出锅']},
  {id:'s42',name:'油焖笋',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:180,tags:['川菜','素菜'],isSichuan:true,ingredients:['春笋','酱油','糖','葱','油'],steps:['笋切块焯水','热油煸炒','加酱油糖焖5分钟','收汁撒葱花']},
  {id:'s43',name:'糊辣莲白',cuisine:'川菜',difficulty:'简单',cookTime:8,calories:120,tags:['川菜','素菜'],isSichuan:true,ingredients:['卷心菜','干辣椒','花椒','醋','盐','糖'],steps:['卷心菜手撕成片','干辣椒花椒爆香','加卷心菜大火快炒','加醋盐糖调味出锅']},
  {id:'s44',name:'三椒牛肉',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:320,tags:['川菜','快手'],isSichuan:true,ingredients:['牛肉','青椒','红椒','泡椒','姜','蒜','酱油','淀粉'],steps:['牛肉切丝腌制','三椒切丝','热油炒牛肉变色','加三椒姜蒜翻炒','调味出锅']},
  {id:'s45',name:'麻辣豆腐干',cuisine:'川菜',difficulty:'简单',cookTime:10,calories:200,tags:['川菜','素菜'],isSichuan:true,ingredients:['豆腐干','辣椒面','花椒粉','盐','糖','油'],steps:['豆腐干切条','热油炸至表皮微硬','加辣椒面花椒粉盐糖','翻炒均匀出锅']},
  {id:'s46',name:'干锅肥肠',cuisine:'川菜',difficulty:'中等',cookTime:35,calories:480,tags:['川菜','麻辣'],isSichuan:true,ingredients:['猪大肠','洋葱','青椒','干辣椒','花椒','姜','蒜','豆瓣酱'],steps:['肥肠卤熟切段','油炸至金黄','炒香豆瓣酱干辣椒花椒','加洋葱青椒肥肠翻炒']},
  {id:'s47',name:'酸辣粉',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:350,tags:['川菜','面食'],isSichuan:true,ingredients:['红薯粉','肉末','花生碎','榨菜','辣椒油','醋','花椒粉','葱','香菜'],steps:['粉条泡软煮熟','炒香肉末','碗中调辣椒油醋花椒粉','加粉条和汤','加肉末花生碎榨菜葱花']},
  {id:'s48',name:'花椒鱼',cuisine:'川菜',difficulty:'中等',cookTime:25,calories:320,tags:['川菜','麻辣'],isSichuan:true,ingredients:['草鱼','青花椒','干辣椒','姜','蒜','料酒','蛋清','淀粉'],steps:['鱼片腌制','大量青花椒炒香','加水煮开','滑入鱼片煮熟','出锅撒干辣椒浇油']},
  {id:'s49',name:'川味红烧牛腩',cuisine:'川菜',difficulty:'中等',cookTime:60,calories:450,tags:['川菜','大菜'],isSichuan:true,ingredients:['牛腩','土豆','胡萝卜','豆瓣酱','花椒','八角','姜','葱','酱油'],steps:['牛腩切块焯水','炒香豆瓣酱花椒八角','加牛腩翻炒加酱油','加水炖煮40分钟','加土豆胡萝卜再炖20分钟收汁']},
  {id:'s50',name:'火爆腰花',cuisine:'川菜',difficulty:'困难',cookTime:15,calories:300,tags:['川菜','快手'],isSichuan:true,ingredients:['猪腰','干辣椒','花椒','姜','蒜','料酒','酱油','淀粉'],steps:['腰花切花刀腌制','爆香干辣椒花椒','大火爆炒腰花至卷曲','加姜蒜料酒酱油','快速翻炒10秒出锅']},
  {id:'s51',name:'尖椒鸡',cuisine:'川菜',difficulty:'简单',cookTime:20,calories:350,tags:['川菜','快手'],isSichuan:true,ingredients:['鸡腿肉','青尖椒','姜','蒜','料酒','酱油','淀粉'],steps:['鸡腿切丁腌制','尖椒切圈','热油炒鸡丁至金黄','加尖椒姜蒜翻炒','调味出锅']},
  {id:'s52',name:'口水兔丁',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:350,tags:['川菜','凉菜'],isSichuan:true,ingredients:['兔肉','花生碎','芝麻','辣椒油','花椒油','酱油','醋','糖','葱'],steps:['兔肉煮熟去骨切丁','调口水汁','浇在兔丁上','撒花生碎芝麻葱花']},
  {id:'s53',name:'啤酒鸭',cuisine:'川菜',difficulty:'中等',cookTime:50,calories:400,tags:['川菜','大菜'],isSichuan:true,ingredients:['鸭肉','啤酒','干辣椒','花椒','姜','蒜','八角','酱油','糖'],steps:['鸭肉焯水','煸炒出油','加干辣椒花椒姜蒜八角','加啤酒没过鸭肉','炖煮30-40分钟','收汁出锅']},
  {id:'s54',name:'麻辣小龙虾',cuisine:'川菜',difficulty:'中等',cookTime:30,calories:350,tags:['川菜','麻辣'],isSichuan:true,ingredients:['小龙虾','干辣椒','花椒','豆瓣酱','姜','蒜','啤酒','十三香'],steps:['小龙虾刷净','油炸至变红','炒香豆瓣酱干辣椒花椒','加小龙虾翻炒','加啤酒十三香焖15分钟']},
  {id:'s55',name:'川味凉面',cuisine:'川菜',difficulty:'简单',cookTime:15,calories:350,tags:['川菜','面食'],isSichuan:true,ingredients:['面条','豆芽','黄瓜','辣椒油','花椒油','酱油','醋','糖','花生碎'],steps:['面条煮熟过凉水','豆芽焯水','黄瓜切丝','调麻辣汁浇在面上','加配菜花生碎拌匀']},
  // ============ 减脂餐 (50道) ============
  {id:'d1',name:'鸡胸肉沙拉',cuisine:'西式',difficulty:'简单',cookTime:15,calories:250,tags:['减脂','轻食'],isDiet:true,ingredients:['鸡胸肉','生菜','圣女果','黄瓜','玉米粒','橄榄油','柠檬汁','盐','黑胡椒'],steps:['鸡胸肉煎熟切块','生菜圣女果黄瓜切好','加玉米粒','淋橄榄油柠檬汁','撒盐黑胡椒拌匀']},
  {id:'d2',name:'三文鱼轻食',cuisine:'西式',difficulty:'简单',cookTime:20,calories:320,tags:['减脂','轻食'],isDiet:true,ingredients:['三文鱼','芦笋','小番茄','柠檬','橄榄油','盐','黑胡椒'],steps:['三文鱼煎至两面金黄','芦笋焯水','摆盘淋柠檬汁','撒盐黑胡椒']},
  {id:'d3',name:'西兰花炒牛肉',cuisine:'中式',difficulty:'简单',cookTime:15,calories:300,tags:['减脂','高蛋白'],isDiet:true,ingredients:['西兰花','牛肉','蒜','酱油','料酒','淀粉','橄榄油'],steps:['牛肉切片腌制','西兰花焯水','热油炒牛肉变色','加西兰花蒜末翻炒','调味出锅']},
  {id:'d4',name:'虾仁藜麦碗',cuisine:'西式',difficulty:'简单',cookTime:25,calories:350,tags:['减脂','轻食'],isDiet:true,ingredients:['虾仁','藜麦','牛油果','圣女果','黄瓜','柠檬汁','盐'],steps:['藜麦煮熟','虾仁煎熟','牛油果圣女果黄瓜切丁','所有食材混合','淋柠檬汁调味']},
  {id:'d5',name:'牛油果鸡蛋',cuisine:'西式',difficulty:'简单',cookTime:10,calories:280,tags:['减脂','早餐'],isDiet:true,ingredients:['牛油果','鸡蛋','全麦面包','盐','黑胡椒'],steps:['鸡蛋煮熟切片','牛油果切片','全麦面包烤至微焦','摆盘撒盐黑胡椒']},
  {id:'d6',name:'蒸鲈鱼',cuisine:'中式',difficulty:'简单',cookTime:15,calories:220,tags:['减脂','高蛋白'],isDiet:true,ingredients:['鲈鱼','姜','葱','蒸鱼豉油','料酒'],steps:['鲈鱼改刀抹料酒','放姜片葱段','上汽蒸8-10分钟','倒掉汁水淋蒸鱼豉油','浇热油']},
  {id:'d7',name:'番茄龙利鱼',cuisine:'中式',difficulty:'简单',cookTime:20,calories:260,tags:['减脂','低卡'],isDiet:true,ingredients:['龙利鱼','番茄','番茄酱','姜','葱','盐','白胡椒粉'],steps:['龙利鱼切块腌制','番茄去皮切块','炒番茄出汁加番茄酱','加适量水煮开','放入鱼块煮3分钟','调味撒葱花']},
  {id:'d8',name:'芦笋炒虾仁',cuisine:'中式',difficulty:'简单',cookTime:10,calories:200,tags:['减脂','高蛋白'],isDiet:true,ingredients:['芦笋','虾仁','蒜','盐','料酒','橄榄油'],steps:['芦笋切段焯水','虾仁腌制','热油炒香蒜末','加虾仁炒变色','加芦笋翻炒调味出锅']},
  {id:'d9',name:'鸡胸肉糙米碗',cuisine:'中式',difficulty:'简单',cookTime:30,calories:380,tags:['减脂','轻食'],isDiet:true,ingredients:['鸡胸肉','糙米','西兰花','胡萝卜','酱油','料酒'],steps:['糙米提前浸泡煮熟','鸡胸肉腌制煎熟切块','西兰花胡萝卜焯水','摆盘搭配']},
  {id:'d10',name:'凉拌黄瓜鸡丝',cuisine:'中式',difficulty:'简单',cookTime:15,calories:220,tags:['减脂','低卡'],isDiet:true,ingredients:['鸡胸肉','黄瓜','蒜','醋','酱油','辣椒油(少)','芝麻'],steps:['鸡胸肉煮熟撕成丝','黄瓜切丝','调汁蒜醋酱油','拌匀撒芝麻']},
  {id:'d11',name:'清蒸龙利鱼',cuisine:'中式',difficulty:'简单',cookTime:12,calories:200,tags:['减脂','高蛋白'],isDiet:true,ingredients:['龙利鱼','姜','葱','蒸鱼豉油','料酒'],steps:['鱼抹料酒放姜丝','上汽蒸8分钟','倒汁撒葱丝','淋蒸鱼豉油浇热油']},
  {id:'d12',name:'藜麦鸡胸肉沙拉',cuisine:'西式',difficulty:'简单',cookTime:25,calories:350,tags:['减脂','轻食'],isDiet:true,ingredients:['鸡胸肉','藜麦','圣女果','黄瓜','生菜','橄榄油','柠檬汁'],steps:['藜麦煮熟','鸡胸肉煎熟切块','蔬菜切好','所有食材混合淋油醋汁']},
  {id:'d13',name:'白灼虾',cuisine:'中式',difficulty:'简单',cookTime:8,calories:180,tags:['减脂','高蛋白'],isDiet:true,ingredients:['基围虾','姜','葱','料酒','生抽'],steps:['虾处理干净','水加姜葱料酒煮开','虾煮熟变红捞出','蘸生抽食用']},
  {id:'d14',name:'清炒时蔬',cuisine:'中式',difficulty:'简单',cookTime:8,calories:120,tags:['减脂','素菜'],isDiet:true,ingredients:['西兰花','胡萝卜','木耳','蒜','盐','橄榄油'],steps:['所有蔬菜切好焯水','热油炒香蒜末','加蔬菜快速翻炒','加盐调味出锅']},
  {id:'d15',name:'鸡蛋蔬菜卷',cuisine:'西式',difficulty:'简单',cookTime:15,calories:250,tags:['减脂','早餐'],isDiet:true,ingredients:['鸡蛋','生菜','番茄','全麦饼','盐','黑胡椒'],steps:['鸡蛋打散摊成蛋饼','全麦饼稍加热','放生菜番茄蛋饼','卷起切段']},
  {id:'d16',name:'三文鱼牛油果碗',cuisine:'西式',difficulty:'简单',cookTime:15,calories:380,tags:['减脂','轻食'],isDiet:true,ingredients:['三文鱼','牛油果','糙米','黄瓜','芝麻','酱油'],steps:['三文鱼煎熟','牛油果切片','糙米打底','摆盘淋酱油撒芝麻']},
  {id:'d17',name:'豆腐蔬菜汤',cuisine:'中式',difficulty:'简单',cookTime:15,calories:150,tags:['减脂','低卡'],isDiet:true,ingredients:['嫩豆腐','白菜','香菇','姜','盐','葱花'],steps:['豆腐切块','白菜香菇切好','水开下姜片香菇','加豆腐白菜煮5分钟','盐调味撒葱花']},
  {id:'d18',name:'烤鸡胸肉',cuisine:'西式',difficulty:'简单',cookTime:25,calories:280,tags:['减脂','高蛋白'],isDiet:true,ingredients:['鸡胸肉','橄榄油','盐','黑胡椒','迷迭香','蒜'],steps:['鸡胸肉用盐黑胡椒橄榄油腌制','烤箱预热200度','烤20分钟','切片装盘']},
  {id:'d19',name:'番茄鸡蛋汤',cuisine:'中式',difficulty:'简单',cookTime:10,calories:120,tags:['减脂','低卡'],isDiet:true,ingredients:['番茄','鸡蛋','葱','盐','香油'],steps:['番茄切块炒出汁','加水煮开','淋入蛋液','盐调味撒葱花淋香油']},
  {id:'d20',name:'虾仁豆腐蒸蛋',cuisine:'中式',difficulty:'简单',cookTime:15,calories:220,tags:['减脂','高蛋白'],isDiet:true,ingredients:['鸡蛋','虾仁','嫩豆腐','盐','葱花','生抽'],steps:['鸡蛋打散加水','嫩豆腐切块放入','虾仁摆上面','蒸10-12分钟','淋生抽撒葱花']},
  {id:'d21',name:'黄瓜拌木耳',cuisine:'中式',difficulty:'简单',cookTime:8,calories:100,tags:['减脂','凉菜'],isDiet:true,ingredients:['黄瓜','木耳','蒜','醋','生抽','香油'],steps:['木耳泡发焯水','黄瓜拍碎','加蒜末醋生抽香油','拌匀即可']},
  {id:'d22',name:'南瓜藜麦沙拉',cuisine:'西式',difficulty:'简单',cookTime:25,calories:320,tags:['减脂','轻食'],isDiet:true,ingredients:['南瓜','藜麦','芝麻菜','羊奶酪','橄榄油','盐','黑胡椒'],steps:['南瓜切块烤熟','藜麦煮熟','芝麻菜打底','加南瓜藜麦羊奶酪','淋橄榄油调味']},
  {id:'d23',name:'清蒸鳕鱼',cuisine:'中式',difficulty:'简单',cookTime:12,calories:200,tags:['减脂','高蛋白'],isDiet:true,ingredients:['鳕鱼','姜','葱','蒸鱼豉油','料酒'],steps:['鳕鱼抹料酒放姜片','蒸8分钟','倒汁撒葱丝','淋蒸鱼豉油浇热油']},
  {id:'d24',name:'凉拌鸡胸肉',cuisine:'中式',difficulty:'简单',cookTime:15,calories:250,tags:['减脂','高蛋白'],isDiet:true,ingredients:['鸡胸肉','黄瓜','香菜','蒜','生抽','醋','辣椒油(少)'],steps:['鸡胸肉煮熟撕丝','黄瓜切丝','加香菜蒜末','调汁拌匀']},
  {id:'d25',name:'番茄牛肉汤',cuisine:'中式',difficulty:'中等',cookTime:40,calories:320,tags:['减脂','高蛋白'],isDiet:true,ingredients:['牛腩','番茄','土豆','胡萝卜','姜','盐'],steps:['牛腩焯水切块','番茄炒出汁','加牛腩和水炖30分钟','加土豆胡萝卜再炖10分钟','盐调味']},
  {id:'d26',name:'芹菜炒香干',cuisine:'中式',difficulty:'简单',cookTime:10,calories:180,tags:['减脂','素菜'],isDiet:true,ingredients:['芹菜','香干','蒜','盐','生抽','橄榄油'],steps:['芹菜切段香干切条','热油炒香蒜末','加香干翻炒','加芹菜炒断生','调味出锅']},
  {id:'d27',name:'紫菜蛋花汤',cuisine:'中式',difficulty:'简单',cookTime:5,calories:80,tags:['减脂','低卡'],isDiet:true,ingredients:['紫菜','鸡蛋','虾皮','盐','香油','葱花'],steps:['水开下紫菜虾皮','淋入蛋液','盐调味','撒葱花淋香油']},
  {id:'d28',name:'黑椒牛肉粒',cuisine:'中式',difficulty:'简单',cookTime:12,calories:300,tags:['减脂','高蛋白'],isDiet:true,ingredients:['牛里脊','黑胡椒','蒜','生抽','料酒','橄榄油'],steps:['牛里脊切粒腌制','热油煎牛肉粒','加黑胡椒蒜末翻炒','调味出锅']},
  {id:'d29',name:'金枪鱼沙拉',cuisine:'西式',difficulty:'简单',cookTime:8,calories:280,tags:['减脂','轻食'],isDiet:true,ingredients:['金枪鱼罐头','生菜','圣女果','玉米粒','橄榄油','柠檬汁'],steps:['生菜圣女果切好','加金枪鱼玉米粒','淋橄榄油柠檬汁','拌匀即可']},
  {id:'d30',name:'口蘑鸡肉烩',cuisine:'西式',difficulty:'简单',cookTime:20,calories:280,tags:['减脂','高蛋白'],isDiet:true,ingredients:['鸡胸肉','口蘑','洋葱','蒜','橄榄油','盐','黑胡椒','百里香'],steps:['鸡胸肉切块腌制','口蘑切片','橄榄油炒香洋葱蒜','加鸡肉变色','加口蘑炒熟调味']},
  {id:'d31',name:'秋葵炒鸡蛋',cuisine:'中式',difficulty:'简单',cookTime:8,calories:160,tags:['减脂','快手'],isDiet:true,ingredients:['秋葵','鸡蛋','蒜','盐','橄榄油'],steps:['秋葵焯水切片','鸡蛋打散炒熟','加秋葵翻炒','调味出锅']},
  {id:'d32',name:'海带豆腐汤',cuisine:'中式',difficulty:'简单',cookTime:12,calories:120,tags:['减脂','低卡'],isDiet:true,ingredients:['海带','豆腐','姜','葱','盐','香油'],steps:['海带泡发切块','豆腐切块','水开下姜片海带煮5分钟','加豆腐再煮3分钟','盐调味撒葱花淋香油']},
  {id:'d33',name:'瘦牛肉沙拉',cuisine:'西式',difficulty:'简单',cookTime:15,calories:320,tags:['减脂','高蛋白'],isDiet:true,ingredients:['牛腱子','生菜','圣女果','黄瓜','油醋汁'],steps:['牛腱子卤熟切片','蔬菜切好','组合淋油醋汁']},
  {id:'d34',name:'西葫芦炒虾仁',cuisine:'中式',difficulty:'简单',cookTime:10,calories:180,tags:['减脂','快手'],isDiet:true,ingredients:['西葫芦','虾仁','蒜','盐','料酒'],steps:['西葫芦切片','虾仁腌制','热油炒虾仁变色','加西葫芦蒜片翻炒','调味出锅']},
  {id:'d35',name:'红薯鸡胸沙拉',cuisine:'西式',difficulty:'简单',cookTime:30,calories:380,tags:['减脂','轻食'],isDiet:true,ingredients:['红薯','鸡胸肉','生菜','圣女果','橄榄油','盐'],steps:['红薯烤熟切块','鸡胸肉煎熟切块','生菜圣女果打底','加红薯鸡胸肉淋橄榄油']},
  {id:'d36',name:'清蒸多宝鱼',cuisine:'中式',difficulty:'简单',cookTime:15,calories:220,tags:['减脂','高蛋白'],isDiet:true,ingredients:['多宝鱼','姜','葱','蒸鱼豉油','料酒'],steps:['多宝鱼抹料酒放姜片','上汽蒸10分钟','倒汁撒葱丝','淋蒸鱼豉油浇热油']},
  {id:'d37',name:'蘑菇鸡肉汤',cuisine:'西式',difficulty:'简单',cookTime:20,calories:200,tags:['减脂','低卡'],isDiet:true,ingredients:['鸡胸肉','蘑菇','洋葱','姜','盐','白胡椒粉'],steps:['鸡胸肉切丁','蘑菇切片','热油炒香洋葱','加水煮开','加鸡肉蘑菇煮熟调味']},
  {id:'d38',name:'手撕包菜(少油)',cuisine:'中式',difficulty:'简单',cookTime:8,calories:120,tags:['减脂','素菜'],isDiet:true,ingredients:['卷心菜','干辣椒','蒜','醋','盐','橄榄油'],steps:['卷心菜手撕成片','少油炒香干辣椒蒜','加卷心菜大火快炒','加醋盐调味出锅']},
  {id:'d39',name:'虾仁西兰花',cuisine:'中式',difficulty:'简单',cookTime:12,calories:200,tags:['减脂','高蛋白'],isDiet:true,ingredients:['虾仁','西兰花','蒜','盐','料酒','橄榄油'],steps:['西兰花焯水','虾仁腌制','热油炒香蒜末','加虾仁炒变色','加西兰花翻炒调味']},
  {id:'d40',name:'玉米排骨汤(去油)',cuisine:'中式',difficulty:'中等',cookTime:60,calories:280,tags:['减脂','汤品'],isDiet:true,ingredients:['排骨','玉米','胡萝卜','姜','枸杞','盐'],steps:['排骨焯水去浮沫','加姜片足量水','炖40分钟','加玉米胡萝卜再炖20分钟','去浮油加盐调味']},
  {id:'d41',name:'牛油果鸡肉卷',cuisine:'西式',difficulty:'简单',cookTime:15,calories:350,tags:['减脂','轻食'],isDiet:true,ingredients:['鸡胸肉','牛油果','全麦饼','生菜','番茄','低脂沙拉酱'],steps:['鸡胸肉煎熟切条','牛油果压泥','全麦饼涂牛油果泥','放生菜鸡肉番茄卷起']},
  {id:'d42',name:'彩椒鸡丁',cuisine:'中式',difficulty:'简单',cookTime:12,calories:250,tags:['减脂','快手'],isDiet:true,ingredients:['鸡胸肉','彩椒','蒜','生抽','料酒','橄榄油'],steps:['鸡胸肉切丁腌制','彩椒切丁','热油炒鸡丁变色','加彩椒蒜末翻炒','调味出锅']},
  {id:'d43',name:'番茄鸡胸肉',cuisine:'中式',difficulty:'简单',cookTime:15,calories:250,tags:['减脂','低卡'],isDiet:true,ingredients:['鸡胸肉','番茄','番茄酱','蒜','盐','黑胡椒'],steps:['鸡胸肉切块腌制','番茄去皮切块','炒番茄出汁加番茄酱','加鸡胸肉煮熟','调味收汁']},
  {id:'d44',name:'蒜蓉生菜',cuisine:'中式',difficulty:'简单',cookTime:5,calories:80,tags:['减脂','素菜'],isDiet:true,ingredients:['生菜','蒜','蚝油(少)','生抽','橄榄油'],steps:['生菜焯水摆盘','蒜切末','少油炒香蒜末','加蚝油生抽调汁浇上']},
  {id:'d45',name:'豆腐牛肉末',cuisine:'中式',difficulty:'简单',cookTime:12,calories:300,tags:['减脂','高蛋白'],isDiet:true,ingredients:['嫩豆腐','牛肉末','蒜','生抽','料酒','葱花'],steps:['豆腐切块焯水','少油炒牛肉末','加蒜末生抽','加豆腐轻轻翻炒','撒葱花出锅']},
  {id:'d46',name:'菠菜鸡蛋沙拉',cuisine:'西式',difficulty:'简单',cookTime:10,calories:220,tags:['减脂','轻食'],isDiet:true,ingredients:['菠菜','鸡蛋','圣女果','橄榄油','醋','盐','黑胡椒'],steps:['菠菜焯水','鸡蛋煮熟切片','圣女果切半','淋油醋汁拌匀']},
  {id:'d47',name:'冬瓜虾仁汤',cuisine:'中式',difficulty:'简单',cookTime:12,calories:100,tags:['减脂','低卡'],isDiet:true,ingredients:['冬瓜','虾仁','姜','盐','葱花'],steps:['冬瓜去皮切片','水开下姜片冬瓜','煮至透明加虾仁','虾仁变红调味撒葱花']},
  {id:'d48',name:'彩椒炒牛肉',cuisine:'中式',difficulty:'简单',cookTime:12,calories:300,tags:['减脂','高蛋白'],isDiet:true,ingredients:['牛肉','彩椒','蒜','生抽','料酒','橄榄油'],steps:['牛肉切丝腌制','彩椒切丝','热油炒牛肉变色','加彩椒蒜末翻炒','调味出锅']},
  {id:'d49',name:'羽衣甘蓝沙拉',cuisine:'西式',difficulty:'简单',cookTime:10,calories:250,tags:['减脂','轻食'],isDiet:true,ingredients:['羽衣甘蓝','鸡胸肉','杏仁片','蔓越莓干','橄榄油','柠檬汁'],steps:['羽衣甘蓝洗净撕小','鸡胸肉煮熟切片','加杏仁片蔓越莓','淋油醋汁拌匀']},
  {id:'d50',name:'清炒豆苗',cuisine:'中式',difficulty:'简单',cookTime:5,calories:80,tags:['减脂','素菜'],isDiet:true,ingredients:['豆苗','蒜','盐','橄榄油'],steps:['热油炒香蒜末','加豆苗大火快炒','加盐调味快速出锅']},

  // ============ 家常快手菜 (30道) ============
  {id:'q1',name:'番茄炒蛋',cuisine:'中式',difficulty:'简单',cookTime:10,calories:220,tags:['家常','快手'],isQuick:true,ingredients:['番茄','鸡蛋','葱','盐','糖','油'],steps:['鸡蛋打散炒熟盛出','番茄切块炒出汁','加鸡蛋翻炒','加盐糖调味撒葱花']},
  {id:'q2',name:'青椒肉丝',cuisine:'中式',difficulty:'简单',cookTime:12,calories:300,tags:['家常','快手'],isQuick:true,ingredients:['猪里脊','青椒','姜','蒜','生抽','料酒','淀粉'],steps:['肉丝腌制','青椒切丝','热油炒肉丝变色','加青椒姜蒜翻炒','调味出锅']},
  {id:'q3',name:'可乐鸡翅',cuisine:'中式',difficulty:'简单',cookTime:25,calories:350,tags:['家常','快手'],isQuick:true,ingredients:['鸡翅','可乐','姜','料酒','酱油','芝麻'],steps:['鸡翅两面煎金黄','加姜料酒酱油','加可乐没过鸡翅','中小火煮15分钟','大火收汁撒芝麻']},
  {id:'q4',name:'酸辣土豆丝',cuisine:'中式',difficulty:'简单',cookTime:10,calories:200,tags:['家常','快手'],isQuick:true,ingredients:['土豆','干辣椒','花椒','醋','盐','蒜'],steps:['土豆切丝泡水去淀粉','热油爆香干辣椒花椒','加土豆丝大火快炒','加醋盐蒜翻炒出锅']},
  {id:'q5',name:'葱花蛋饼',cuisine:'中式',difficulty:'简单',cookTime:8,calories:200,tags:['家常','快手'],isQuick:true,ingredients:['鸡蛋','面粉','葱','盐','水','油'],steps:['鸡蛋打散加面粉水调糊','加葱花盐拌匀','平底锅摊薄饼','两面金黄出锅']},
  {id:'q6',name:'蒜蓉西兰花',cuisine:'中式',difficulty:'简单',cookTime:8,calories:120,tags:['家常','快手'],isQuick:true,ingredients:['西兰花','蒜','盐','生抽','油'],steps:['西兰花掰小朵焯水','热油炒香蒜末','加西兰花翻炒','调味出锅']},
  {id:'q7',name:'酱油炒饭',cuisine:'中式',difficulty:'简单',cookTime:8,calories:350,tags:['家常','快手'],isQuick:true,ingredients:['米饭','鸡蛋','酱油','葱','油'],steps:['鸡蛋炒碎盛出','热油炒米饭','加酱油翻炒均匀','加鸡蛋葱花炒匀']},
  {id:'q8',name:'葱爆牛肉',cuisine:'中式',difficulty:'简单',cookTime:10,calories:320,tags:['家常','快手'],isQuick:true,ingredients:['牛肉','大葱','姜','生抽','料酒','淀粉'],steps:['牛肉切片腌制','大葱切段','大火爆炒牛肉变色','加大葱翻炒','调味快速出锅']},
  {id:'q9',name:'蚝油生菜',cuisine:'中式',difficulty:'简单',cookTime:5,calories:100,tags:['家常','快手'],isQuick:true,ingredients:['生菜','蚝油','蒜','生抽','糖'],steps:['生菜焯水摆盘','蒜末炒香加蚝油生抽糖','调汁浇在生菜上']},
  {id:'q10',name:'蛋炒饭',cuisine:'中式',difficulty:'简单',cookTime:8,calories:380,tags:['家常','快手'],isQuick:true,ingredients:['米饭','鸡蛋','葱','盐','油'],steps:['鸡蛋炒散','热油炒米饭','加鸡蛋翻炒','加盐撒葱花出锅']},
  {id:'q11',name:'红烧鸡翅',cuisine:'中式',difficulty:'简单',cookTime:25,calories:350,tags:['家常','快手'],isQuick:true,ingredients:['鸡翅','酱油','冰糖','姜','料酒','八角'],steps:['鸡翅煎金黄','加姜八角','加酱油料酒冰糖','加水焖15分钟','收汁出锅']},
  {id:'q12',name:'蒜蓉空心菜',cuisine:'中式',difficulty:'简单',cookTime:5,calories:100,tags:['家常','快手'],isQuick:true,ingredients:['空心菜','蒜','盐','油'],steps:['热油炒香蒜末','加空心菜大火快炒','加盐调味快速出锅']},
  {id:'q13',name:'洋葱炒蛋',cuisine:'中式',difficulty:'简单',cookTime:8,calories:200,tags:['家常','快手'],isQuick:true,ingredients:['洋葱','鸡蛋','盐','油'],steps:['鸡蛋炒熟盛出','洋葱切丝炒软','加鸡蛋翻炒','加盐调味出锅']},
  {id:'q14',name:'家常豆腐',cuisine:'中式',difficulty:'简单',cookTime:12,calories:250,tags:['家常','快手'],isQuick:true,ingredients:['老豆腐','青椒','木耳','豆瓣酱','蒜','生抽'],steps:['豆腐切片煎两面黄','炒香豆瓣酱蒜','加青椒木耳翻炒','加豆腐轻轻翻炒','调味出锅']},
  {id:'q15',name:'西红柿鸡蛋面',cuisine:'中式',difficulty:'简单',cookTime:15,calories:350,tags:['家常','快手'],isQuick:true,ingredients:['面条','番茄','鸡蛋','葱','盐','油'],steps:['番茄炒出汁加水煮开','淋蛋液','下面条煮熟','盐调味撒葱花']},
  {id:'q16',name:'蒜苔炒肉',cuisine:'中式',difficulty:'简单',cookTime:12,calories:300,tags:['家常','快手'],isQuick:true,ingredients:['猪里脊','蒜苔','姜','生抽','料酒','淀粉'],steps:['肉丝腌制','蒜苔切段','热油炒肉丝变色','加蒜苔姜丝翻炒','调味出锅']},
  {id:'q17',name:'家常炒合菜',cuisine:'中式',difficulty:'简单',cookTime:10,calories:220,tags:['家常','快手'],isQuick:true,ingredients:['绿豆芽','粉丝','韭菜','鸡蛋','生抽','盐'],steps:['鸡蛋炒熟','粉丝泡软','豆芽韭菜炒断生','加粉丝鸡蛋翻炒','调味出锅']},
  {id:'q18',name:'红烧豆腐',cuisine:'中式',difficulty:'简单',cookTime:10,calories:220,tags:['家常','快手'],isQuick:true,ingredients:['嫩豆腐','葱','生抽','老抽','糖','淀粉'],steps:['豆腐切块焯水','调红烧汁：生抽老抽糖水','煮开放豆腐','小火煮5分钟勾芡','撒葱花']},
  {id:'q19',name:'土豆炖牛肉',cuisine:'中式',difficulty:'中等',cookTime:40,calories:420,tags:['家常','下饭'],isQuick:true,ingredients:['牛腩','土豆','胡萝卜','姜','八角','酱油','料酒'],steps:['牛腩焯水切块','炒姜八角加牛腩','加酱油料酒加水炖30分钟','加土豆胡萝卜再炖10分钟','收汁']},
  {id:'q20',name:'西葫芦炒鸡蛋',cuisine:'中式',difficulty:'简单',cookTime:8,calories:180,tags:['家常','快手'],isQuick:true,ingredients:['西葫芦','鸡蛋','蒜','盐','油'],steps:['鸡蛋炒熟','西葫芦切片','热油炒香蒜末','加西葫芦炒软','加鸡蛋调味出锅']},
  {id:'q21',name:'红烧肉',cuisine:'中式',difficulty:'中等',cookTime:60,calories:500,tags:['家常','经典'],isQuick:true,ingredients:['五花肉','冰糖','酱油','料酒','姜','八角','桂皮'],steps:['五花肉切块焯水','炒糖色','加五花肉上色','加酱油料酒姜八角桂皮','加水炖50分钟','收汁出锅']},
  {id:'q22',name:'皮蛋豆腐',cuisine:'中式',difficulty:'简单',cookTime:5,calories:180,tags:['家常','凉菜'],isQuick:true,ingredients:['内酯豆腐','皮蛋','葱花','生抽','香油','辣椒油'],steps:['豆腐切片摆盘','皮蛋切碎放豆腐上','淋生抽香油辣椒油','撒葱花']},
  {id:'q23',name:'糖拌番茄',cuisine:'中式',difficulty:'简单',cookTime:3,calories:100,tags:['家常','凉菜'],isQuick:true,ingredients:['番茄','白糖'],steps:['番茄切片摆盘','撒上白糖即可']},
  {id:'q24',name:'清炒油菜',cuisine:'中式',difficulty:'简单',cookTime:5,calories:80,tags:['家常','快手'],isQuick:true,ingredients:['油菜','蒜','盐','油'],steps:['热油炒香蒜末','加油菜大火快炒','加盐调味出锅']},
  {id:'q25',name:'鸡蛋羹',cuisine:'中式',difficulty:'简单',cookTime:12,calories:150,tags:['家常','快手'],isQuick:true,ingredients:['鸡蛋','温水','盐','生抽','香油','葱花'],steps:['鸡蛋打散加温水盐','过滤去泡沫','盖保鲜膜蒸10分钟','淋生抽香油撒葱花']},
  {id:'q26',name:'酱油鸡翅',cuisine:'中式',difficulty:'简单',cookTime:20,calories:320,tags:['家常','快手'],isQuick:true,ingredients:['鸡翅','生抽','老抽','姜','料酒','糖'],steps:['鸡翅划刀','加生抽老抽姜料酒糖腌制','煎两面金黄','加腌汁和少量水焖10分钟','收汁']},
  {id:'q27',name:'葱花饼',cuisine:'中式',difficulty:'简单',cookTime:15,calories:280,tags:['家常','快手'],isQuick:true,ingredients:['面粉','葱','盐','油','水'],steps:['面粉加水和成面团','擀薄抹油撒葱花盐','卷起再擀平','煎至两面金黄']},
  {id:'q28',name:'玉米排骨汤',cuisine:'中式',difficulty:'简单',cookTime:50,calories:350,tags:['家常','汤品'],isQuick:true,ingredients:['排骨','玉米','胡萝卜','姜','盐','枸杞'],steps:['排骨焯水','加姜片足量水煮开','转小火炖30分钟','加玉米胡萝卜再炖15分钟','加枸杞盐调味']},
  {id:'q29',name:'木耳炒鸡蛋',cuisine:'中式',difficulty:'简单',cookTime:8,calories:180,tags:['家常','快手'],isQuick:true,ingredients:['木耳','鸡蛋','青椒','蒜','盐','油'],steps:['木耳泡发撕小','鸡蛋炒熟','热油炒香蒜青椒','加木耳翻炒','加鸡蛋调味出锅']},
  {id:'q30',name:'黄焖鸡',cuisine:'中式',difficulty:'中等',cookTime:30,calories:380,tags:['家常','下饭'],isQuick:true,ingredients:['鸡腿','土豆','青椒','干辣椒','姜','蒜','酱油','料酒'],steps:['鸡腿切块焯水','炒姜蒜干辣椒','加鸡块翻炒加酱油料酒','加水没过炖15分钟','加土豆再炖10分钟','加青椒收汁']},
];

// 初始化：如果本地存储没有菜谱数据，则导入内置菜谱
function initRecipeData() {
  const stored = localStorage.getItem('fridge_recipes');
  if (!stored || JSON.parse(stored).length === 0) {
    localStorage.setItem('fridge_recipes', JSON.stringify(RecipeDB));
  }
}

// 暴露到全局
window.RecipeDB = RecipeDB;
window.initRecipeData = initRecipeData;
